language: node_js
node_js:
  - '5.1'
before_script:
  - npm install -g gulp bower
  - npm install
  - bower install
script: gulp
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master